//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discrepancia
    {
        public int Id { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tipo { get; set; }
    }
}
