//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id { get; set; }
        public string Contraseña { get; set; }
        public string NombreDeUsuario { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModicacion { get; set; }
        public string Creador { get; set; }
        public bool Activo { get; set; }
        public string TipoDeEmpleado { get; set; }
    
        public virtual Pedido Pedidos { get; set; }
    }
}
