//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iva
    {
        public int Id { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public double Valor { get; set; }
        public string Creador { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public bool Activo { get; set; }
    }
}
