//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDeDatosContainer : DbContext
    {
        public ModeloDeDatosContainer()
            : base("name=ModeloDeDatosContainer")
        {
            var instance = System.Data.Entity.SqlServer.SqlProviderServices.Instance;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingrediente> Ingredientes { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Pedido> Pedidos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Platillo> Platillos { get; set; }
        public virtual DbSet<PlatilloPedido> PlatilloPedido { get; set; }
        public virtual DbSet<PlatilloIngrediente> PlatilloIngrediente { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<ProductoPedido> ProductoPedido { get; set; }
        public virtual DbSet<Iva> Ivas { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<IngredienteIngrediente> IngredienteIngrediente { get; set; }
        public virtual DbSet<Discrepancia> Discrepancias { get; set; }
    }
}
