//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDeDatosContainer : DbContext
    {
        public ModeloDeDatosContainer()
            : base("name=ModeloDeDatosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingrediente> Ingredientes { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Pedido> Pedidoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Alimento> Alimentoes { get; set; }
        public virtual DbSet<AlimentoPedido> AlimentoPedidoes { get; set; }
        public virtual DbSet<AlimentoIngrediente> AlimentoIngredientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ProductoPedido> ProductoPedidoes { get; set; }
        public virtual DbSet<Iva> Ivas { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<IngredienteIngrediente> IngredienteIngredientes { get; set; }
    }
}
