//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionIngrediente
    {
        public int Id { get; set; }
        public double Cantidad { get; set; }
    
        public virtual Ingrediente IngredientePadre { get; set; }
        public virtual Ingrediente IngredienteHijo { get; set; }
    }
}
